--  PROJECT: Hospital Revenue Leakage & Operations Analysis

/*-- PROBLEM STATEMENT : 
   * Stakeholder : Hospital Financial Director & Operations Team
   * Business impact : uncollected bills lock up money the hospital needed to pay its bill, while cancelled appointments mean expensive doctor time goes completely to waste without making any income.
   * Goal : Find where the hospital is losing money from unpaid bills, bad insurance claims, and cancelled appointments
   * Decision / Action to take : Change payment rules to collect money faster and cut revenue losses
   * Data Used : Hospital database tables for billing, appointments, doctors, treatments, and patients


-- DATASET OVERVIEW
   Data source : kaggle
   Row count : patients - 50, billing - 200, appointments - 200, doctors - 10, treatments - 200.
   Key tables and columns : 
-- 1. patients
   - patient_id (PK)       : Unique patient identification
   - first_name, last_name : Patient personal details
   - gender                : gender of the patient
   - date_of_birth         : Used for age group categorization
   - contact_number        : phone number of the patients
   - address               : address of the patient
   - registration_date     : the date of patient registration
   - insurance_provider    : the one who provides insurance to the patients
   - email                 : email of the patients

-- 2. doctors
   - doctor_id (PK)        : Unique physician identification
   - first_name, last_name : Doctor full name
   - specialty             : Department/medical field
   - phone_number          : doctors number
   - years_of_experience   : the doctors experience
   - hospital_branch       : branch in which the doctor work
   - email                 : email address of the doctor

-- 3. appointments
   - appointment_id (PK)   : Unique booking identification
   - patient_id (FK)       : Links to patients table
   - doctor_id (FK)        : Links to doctors table
   - appointment_date      : Scheduled date
   - appointment_time      : Scheduled time
   - status                : Visit state (Completed, Cancelled, No-Show)

-- 4. treatments
   - treatment_id (PK)     : Unique treatment identification
   - appointment_id (FK)   : Links to appointments table
   - treatment_type        : Medical procedure (e.g., MRI, X-Ray)
   - cost                  : Base price of treatment
   - treatment_date        : the day treatment was performed 

-- 5. billing
   - bill_id (PK)          : Unique invoice identification
   - patient_id (FK)       : Links to patients table
   - treatment_id          : links to treatment table
   - bill_date             : the day bill is issued
   - total_amount          : Total billed cost
   - payment_method        : Amount paid by insurance,credit card or cash
   - payment_status        : whether the payment is paid,pending or fail
-- * PK (Primary Key)
-- * FK (Foreign Key)

-- Known data quality issues : 	None

-- BUSINESS QUESTION :
-- 1.what is the total revenue generated by branch and medical specialization?
-- 2.what is the total unpaid balance across insurance providers?
-- 3. what is the appointments completion rate versus cancellation/ no-show rate per doctor?
-- 4.which treatment types that got the highest average cost and volume?
-- 5.what is patient retention rate?
-- 6.what is the rank of each doctor based on their total revenue?
-- 7.How can we segment our patient population by age to design targeted healthcare packages and preventive check-up programs?
-- 8.which treatment got mostly claimed by insurance by patients and what is the total amount?
-- 9.Which top 3 insurance providers represent the highest outstanding paid balances for the hospital?
-- 10.How do unpaid insurance claim rates and payment delays vary across different patient age demographics?*/

create database hospitals;
use hospitals;

-- RETRIEVES ALL RECORDS FROM IMPORTED DATA FROM EXCEL :
SELECT * FROM hospitals.`appoinments copy`;
SELECT * FROM hospitals.`billing copy`;
SELECT * FROM hospitals.`doctors copy`;
SELECT * FROM hospitals.`patients copy`;
SELECT * FROM hospitals.`treatments copy`;

-- TABLE RENAMING INTO CLEAN STANDARDIZED TABLE NAMES :
rename table hospitals.`appoinments copy` to appointments;
rename table hospitals.`billing copy` to billing;
rename table hospitals.`doctors copy` to doctors;
rename table hospitals.`patients copy` to patients;
rename table hospitals.`treatments copy` to treatments;

-- DATA VERIFICATION :
SELECT * FROM appointments;
SELECT * FROM billing;
SELECT * FROM doctors;
SELECT * FROM patients;
SELECT * FROM treatments;

-- NUMBER OF ROWS : 
SELECT count(*) FROM appointments;
SELECT count(*) FROM billing;
SELECT count(*) FROM doctors;
SELECT count(*) FROM patients;
SELECT count(*) FROM treatments;

-- DUPLICATES CHECK :
SELECT *, COUNT(*) AS duplicate_count
FROM appointments
GROUP BY appointment_id, patient_id, doctor_id, appointment_date, appointment_time, reason_for_visit, status
HAVING COUNT(*) > 1;

SELECT *, COUNT(*) AS duplicate_count
FROM billing
GROUP BY bill_id, patient_id, treatment_id, bill_date, amount, payment_method,payment_status
HAVING COUNT(*) > 1;

SELECT *, COUNT(*) AS duplicate_count
FROM doctors
GROUP BY doctor_id, first_name, last_name, specialization, phone_number, years_experience, hospital_branch, email
HAVING COUNT(*) > 1;

SELECT *, COUNT(*) AS duplicate_count
FROM patients
GROUP BY patient_id, first_name, last_name, gender, date_of_birth, contact_number, address, registration_date, insurance_provider, insurance_number, email
HAVING COUNT(*) > 1;

SELECT *, COUNT(*) AS duplicate_count
FROM treatments
GROUP BY treatment_id,appointment_id,treatment_type, description, cost, treatment_date
HAVING COUNT(*) > 1;

-- FINDING NULL VALUES
SELECT *
FROM appointments
WHERE appointment_id IS NULL
   OR patient_id IS NULL
   OR doctor_id IS NULL
   OR appointment_date IS NULL
   OR reason_for_visit IS NULL
   OR status IS NULL;

select *
from  billing
where bill_id is null
   OR patient_id is null
   OR treatment_id IS NULL
   OR bill_date IS NULL
   OR amount IS NULL
   or payment_method is null
   or payment_status is null;

select *
from doctors
where doctor_id is null
or first_name is null
or last_name is null
or specialization is null
or phone_number is null
or years_experience is null
or hospital_branch is null
or email is null;

select *
from patients
where patient_id is null
   or first_name is null
   or last_name is null
   or gender is null
   or date_of_birth is null
   or contact_number is null
   or address is null
   or registration_date is null
   or insurance_provider is null
   or insurance_number is null
   or email is null;
   
   select *
   from treatments
   where treatment_id is null
   or appointment_id is null
   or treatment_type is null
   or description is null
   or cost is null 
   or treatment_date is null;
   
-- FINANCIAL PERFORMANCE AND OPERATIONAL LOSSES 
SELECT 
    CONCAT('$', FORMAT(SUM(amount), 2)) AS gross_billed_revenue,
    CONCAT('$', FORMAT(SUM(CASE WHEN payment_status = 'Paid' THEN amount ELSE 0 END), 2)) AS total_collected_revenue,
    CONCAT('$', FORMAT(SUM(CASE WHEN payment_status = 'Pending' THEN amount ELSE 0 END), 2)) AS total_unpaid_leakage,
    ROUND(100.0 * SUM(CASE WHEN payment_status = 'Pending' THEN amount ELSE 0 END) / SUM(amount), 2) AS unpaid_revenue_pct,
    (SELECT ROUND(100.0 * SUM(CASE WHEN status IN ('Cancelled', 'No-Show') THEN 1 ELSE 0 END) / COUNT(*), 2) FROM appointments) AS appointment_loss_rate_pct
FROM billing;

-- ANSWERING THE BUSINESS QUESTIONS :
-- 1.what is the total revenue generated by branch and medical specialization?
-- (identifying high performing branches and departments)
-- Calculates total paid revenue for each hospital branch and medical department.
SELECT 
    d.hospital_branch,
    d.specialization,
    SUM(b.amount) AS total_revenue
FROM billing b
JOIN hospitals.treatments t ON b.treatment_id = t.treatment_id
JOIN appointments a ON t.appointment_id = a.appointment_id
JOIN doctors d ON a.doctor_id = d.doctor_id
WHERE b.payment_status = 'Paid'
GROUP BY d.hospital_branch, d.specialization
ORDER BY total_revenue DESC;
-- RECOMMENDATIONS/INSIGHTS :
-- * Invest in Pediatrics: Highest revenue (52,623), making it the top-performing department.
-- * Improve Westside Oncology: Low revenue (1,075 vs. 18,935 at Eastside) indicates a need for operational review.
-- * Expand Dermatology at Eastside: Strong performance at other hospitals suggests high revenue potential.

-- 2.what is the total unpaid balance across insurance providers?
-- (pinpoints delayed insurance settlements and uncollected revenue)
-- Shows total pending money and unpaid bill counts grouped by insurance provider.
SELECT 
    p.insurance_provider,
    COUNT(b.bill_id) AS pending_bills,
    SUM(b.amount) AS  unpaid_amount
FROM billing b
JOIN treatments t ON b.treatment_id = t.treatment_id
JOIN appointments a ON t.appointment_id = a.appointment_id
JOIN patients p ON a.patient_id = p.patient_id
WHERE b.payment_status = 'Pending' or 'fail'
GROUP BY p.insurance_provider
ORDER BY unpaid_amount DESC;
-- RECOMMENDATIONS/INSIGHTS :
-- * Prioritize MedCare Plus: Follow up on 27 unpaid bills worth 68,255.
-- * Review WellnessCorp Claims: Check 17 high-value pending claims totaling 52,020.
-- * Verify Insurance Early: Confirm coverage at registration to reduce unpaid bills and payment delays.

-- Operational and doctor productivity analysis
-- 3. what is the appointments completion rate versus cancellation/ no-show rate per doctor?
-- Calculates completion and cancellation percentages for every doctor.
SELECT 
    d.doctor_id AS doctor_id,
    CONCAT(d.first_name, ' ', d.last_name) AS doctor_name,
    COUNT(a.appointment_id) AS total_appointments,
    ROUND(100.0 * SUM(CASE WHEN a.status = 'Completed' THEN 1 ELSE 0 END) / COUNT(a.appointment_id), 2) AS completion_rate_pct,
    ROUND(100.0 * SUM(CASE WHEN a.status IN ('Cancelled', 'No-Show') THEN 1 ELSE 0 END) / COUNT(a.appointment_id), 2) AS cancellation_rate_pct
FROM doctors d
LEFT JOIN appointments a ON d.doctor_id = a.doctor_id
GROUP BY d.doctor_id, d.first_name, d.last_name
ORDER BY cancellation_rate_pct DESC;
-- RECOMMENDATIONS/INSIGHTS :
-- * Send Appointment Reminders: Use SMS/WhatsApp reminders for doctors with high cancellation rates like Linda Brown,David taylor etc.
-- * Review Sarah Taylor's Schedule: Check why her completion rate is low despite having the highest appointments.
-- * Optimize High-Cancellation Slots: Slightly overbook doctors with frequent cancellations to reduce empty appointment slots.

-- 4.which treatment types that got the highest average cost and volume?
-- Counts total procedures, average cost, and overall revenue for each treatment type.
SELECT 
    treatment_type,
    COUNT(treatment_id) AS total_procedures,
    ROUND(AVG(cost), 2) AS avg_treatment_cost,
    SUM(cost) AS total_treatment_revenue
FROM treatments
GROUP BY treatment_type
ORDER BY total_treatment_revenue DESC;
-- RECOMMENDATIONS/INSIGHTS :
-- * Prioritize MRI Maintenance: Keep MRI services running to protect high-value revenue.
-- * Expand Chemotherapy Capacity: Add chairs or nursing support to meet high demand.
-- * Bundle X-Rays & ECGs: Offer combined diagnostic packages to increase revenue.
 
-- 5.what is patient retention rate?
-- (percentage of returning patients vs single-visit patients)?
-- eveluates patient loyalty and long term care continuity
-- Calculates the percentage of returning patients (more than 1 visit) versus single-visit patients.
WITH patient_visits AS (
    SELECT 
        patient_id, 
        COUNT(appointment_id) AS visit_count 
    FROM appointments
    WHERE status = 'Completed'
    GROUP BY patient_id)
SELECT 
    COUNT(CASE WHEN visit_count > 1 THEN 1 END) AS returning_patients,
    COUNT(CASE WHEN visit_count = 1 THEN 1 END) AS single_visit_patients,
    ROUND(100.0 * COUNT(CASE WHEN visit_count > 1 THEN 1 END) / COUNT(*), 2) AS retention_rate_pct
FROM patient_visits;
-- RECOMMENDATIONS :
-- * Send Follow-Up Reminders: Contact one-time patients after 30 days to encourage repeat visits.
-- * Collect Patient Feedback: Survey one-time visitors to understand why they did not return.
-- * Boost Patient Retention: Offer check-up packages or loyalty benefits to increase repeat visits.

-- 6.what is the rank of each doctor based on their total revenue?
-- Ranks doctors from highest to lowest based on total billing revenue generated.
SELECT 
    d.doctor_id,
    d.first_name,
    SUM(b.amount) AS total_revenue,
    RANK() OVER (ORDER BY SUM(b.amount) DESC) AS revenue_rank
FROM billing b
JOIN treatments t 
    ON b.treatment_id= t.treatment_id
JOIN appointments a 
    ON t.appointment_id = a.appointment_id
JOIN doctors d 
    ON a.doctor_id = d.doctor_id
GROUP BY d.doctor_id, d.first_name;
-- RECOMMENDATIONS/INSIGHTS :
-- * Support Top Performer Sarah: Optimize her schedule with admin support to maximize revenue.
-- * Share Best Practices: Let lower-performing doctors learn from the top three earners.
-- * Balance Patient Scheduling: Distribute high-value appointments more evenly across doctors.

-- 7.How can we segment our patient population by age to design targeted healthcare packages and preventive check-up programs?
-- Categorizes every patient into Minor, Adult, or Senior based on their age.
SELECT first_name, last_name, date_of_birth,
TIMESTAMPDIFF(YEAR, date_of_birth, CURDATE()) AS age,
CASE
    WHEN TIMESTAMPDIFF(YEAR, date_of_birth, CURDATE()) < 18 THEN 'Child'
    WHEN TIMESTAMPDIFF(YEAR, date_of_birth, CURDATE()) BETWEEN 18 AND 64 THEN 'Adult'
    ELSE 'Senior'
END AS age_group
FROM patients;
-- RECOMMENDATIONS/INSIGHTS :
-- * Launch Adult Screening Packages: Offer preventive check-ups for adults aged 35–64.
-- * Introduce Senior Care Plans: Provide specialized health packages for patients aged 65+.
-- * Send Milestone Health Reminders: Automate check-up alerts for ages 40, 50, and 65.


-- 8.which treatment got mostly claimed by insurance by patients and what is the total amount?
-- Finds the single treatment type with the highest total amount billed to insurance.
SELECT 
    t.treatment_type,
    COUNT(b.bill_id) AS total_claims,
    SUM(b.amount) AS total_claimed_amount
FROM billing b
JOIN treatments t 
    ON b.treatment_id = t.treatment_id
WHERE b.payment_method = 'Insurance' and payment_status = 'paid'
GROUP BY t.treatment_type
ORDER BY total_claimed_amount DESC
LIMIT 1;
-- RECOMMENDATIONS/INSIGHTS :
-- * Speed Up MRI Approvals: Simplify insurance pre-authorization for faster approvals.
-- * Improve MRI Claim Processing: Create a dedicated billing process for quicker reimbursements.
-- * Promote Insurance Coverage: Inform patients that insurance may cover MRI costs.

-- 9.Which top 3 insurance providers represent the highest outstanding paid balances for the hospital?
-- Finds the top 3 insurance providers with the highest total insurance billing amounts.
SELECT 
    p.patient_id,
    p.first_name,
    p.last_name,
    p.insurance_provider,
    SUM(b.amount) AS total_insurance_amount
FROM billing b
JOIN treatments t ON b.treatment_id = t.treatment_id
JOIN appointments a ON t.appointment_id = a.appointment_id
JOIN patients p ON a.patient_id = p.patient_id
WHERE b.payment_method = 'Insurance' and b.payment_status = 'paid'
GROUP BY p.patient_id, p.first_name, p.last_name, p.insurance_provider
ORDER BY total_insurance_amount DESC
LIMIT 3;
-- RECOMMENDATIONS/INSIGHTS :
-- * Support High-Value Patients: Assign case managers to ensure smooth care and paperwork.
-- * Audit Top Accounts: Review billing records to prevent claim delays.
-- * Offer Payment Counseling: Help patients manage deductibles and uncovered costs.

-- 10.How do unpaid insurance claim rates and payment delays vary across different patient age demographics?
-- Summarizes total insurance claim count and payout amount across 4 age groups.
SELECT 
    CASE 
        WHEN TIMESTAMPDIFF(YEAR, p.date_of_birth, CURDATE()) < 18 THEN 'Minor (Under 18)'
        WHEN TIMESTAMPDIFF(YEAR, p.date_of_birth, CURDATE()) BETWEEN 18 AND 35 THEN 'Young Adult (18-35)'
        WHEN TIMESTAMPDIFF(YEAR, p.date_of_birth, CURDATE()) BETWEEN 36 AND 60 THEN 'Middle Aged (36-60)'
        ELSE 'Senior (60+)'
    END AS age_group,
    COUNT(b.bill_id) AS total_claims,
    SUM(b.amount) AS total_unpaid_amount
FROM billing b
JOIN treatments t ON b.treatment_id = t.treatment_id
JOIN appointments a ON t.appointment_id = a.appointment_id
JOIN patients p ON a.patient_id = p.patient_id
WHERE b.payment_method = 'Insurance' 
  AND b.payment_status IN ('pending', 'failed')
GROUP BY age_group
ORDER BY total_unpaid_amount DESC;
-- RECOMMENDATIONS/INSIGHTS :
-- * Prioritize Young Adults: Focus on 18–35-year-olds, who have over $54,475 in unpaid revenue.
-- * Automate Insurance Checks: Verify insurance and pre-authorization digitally at checkout to prevent claim failures.
-- * Support Seniors: Provide billing help to patients with age 60+ to resolve insurance issues and reduce unpaid balance.


-- WITH ADDITIONAL DATA , I WOULD INVESTIGATE THE FOLLOWING :
--  * Why patients cancel: Track lobby wait times to see if long delays are driving the cancellation rate.
--  * Why insurance isn't paying: Find out if the 180k in unpaid bills is due to wrong coding or missing paperwork.
--  * Actual profit margins: Check equipment and staff costs to see if high-revenue MRIs are actually making real profit.
--  * Where single-visit patients go: Figure out why 64% of patients never come back—are they healed, or just unhappy?

